
version: '3.4'

services:
  nginx:
    image: nginx:1.19.7-alpine
    volumes:
      - ./docker/nginx/conf.d/local.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./public:/code/public:ro
      - ./storage:/code/storage
    ports:
      - "8080:80"

  php-fpm:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
      target: laravel_application_mounted
      args:
        PHP_DEBUGGER: xdebug
        PHP_INIT_SCRIPT: local
    volumes:
      - ./docker/php-fpm/conf.d/local.ini:/usr/local/etc/php/conf.d/custom.ini:ro
      - .:/code:cached
    expose:
      - "9000"
    environment:
      - PHP_IDE_CONFIG=serverName=<project>

  db:
    build: ./docker/mysql
    volumes:
      - db-store:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=db
      - PMA_USER=tutor
      - PMA_PASSWORD=tutor
    ports:
      - "8888:80"
    volumes:
      - ./docker/phpmyadmin/sessions:/sessions

volumes:
  db-store: